YARN-10472. Backport YARN-10314. YarnClient throws NoClassDefFoundError for WebSocketException with only shaded client jars (#2412)
(cherry picked from commit beb6cf6cc2ed829f595f52f883f1526d8444a006)