FIX check TestConfigurationFieldsBase.testCompareXmlAgainstConfigurationClass:527 hdfs-rbf-default.xml has 1 properties missing in  class org.apache.hadoop.hdfs.server.federation.router.RBFConfigKeys Entries:   dfs.federation.router.fairness.handler.proportion.EXAMPLENAMESERVICE expected:<0> but was:<1>