Merged PR 4749143: HDFS-17526. getMetadataInputStream should use getShareDeleteFileInputStream for windows
#What
Use getShareDeleteFileInputStream for windows MetaDataInputStream

[HDFS-17526](https://issues.apache.org/jira/browse/HDFS-17526)
#Why
In our 2.9 branch, we backported [HDFS-10636](https://issues.apache.org/jira/browse/HDFS-10636) but we modified the getMetaDataInputStream() compared to open source. Since this change was never checked in to open-source, branch-3.3-mt does not have this fix for windows.

DN Logs:
```
2024-05-07T19:45:48,429 ERROR [DataXceiver for client DFSClient_iusvr_MWHEEEAP003F671_container_e1349_1715033229940_2291_01_000090_446347524_1 at /2603:10b0:d13:2a:0:0:0:8763:13239 [Receiving block BP-1897851578-10.59.214.126-1624147212071:blk_16605581415_16555930755]] org.apache.hadoop.hdfs.server.datanode.DataNode: MWHEEEAP0028C5A.machines.MWHE01.ap.gbl:10010:DataXceiver error processing WRITE_BLOCK operation  remote: /2603:10b0:d13:2a:0:0:0:8763:13239 local: /2603:10b0:d13:10:0:0:0:1543:10010
java.io.IOException: Block FinalizedReplica, blk_16605581415_16555930755, FINALIZED
  getNumBytes()     = 521615760
  getBytesOnDisk()  = 521615760
  getVisibleLength()= 521615760
  getVolume()       = G:\data\hdfs\data
  getBlockURI()     = file:/G:/data/hdfs/data/current/BP-1897851578-10.59.214.126-1624147212071/current/finalized/subdir5/subdir16/blk_16605581415 reopen failed.  Unable to move meta file  G:\data\hdfs\data\current\BP-1897851578-10.59.214.126-1624147212071\current\finalized\subdir5\subdir16\blk_16605581415_16555930755.meta to G:\data\hdfs\data\current\BP-1897851578-10.59.214.126-1624147212071\current\finalized\subdir5\subdir16\blk_16605581415_16557042956.meta
    at org.apache.hadoop.hdfs.server.datanode.LocalReplica.bumpReplicaGS(LocalReplica.java:385) ~[hadoop-hdfs-3.3.4-MT-SNAPSHOT.jar:?]
    at org.apache.hadoop.hdfs.server.datanode.fsdataset.impl.FsDatasetImpl.recoverClose(FsDatasetImpl.java:1423) ~[hadoop-hdfs-3.3.4-MT-SNAPSHOT.jar:?]
    at org.apache.hadoop.hdfs.server.datanode.DataXceiver.writeBlock(DataXceiver.java:778) ~[hadoop-hdfs-3.3.4-MT-SNAPSHOT.jar:?]
    at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.opWriteBlock(Receiver.java:176) ~[hadoop-hdfs-3.3.4-MT-SNAPSHOT.jar:?]
    at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.processOp(Receiver.java:110) ~[hadoop-hdfs-3.3.4-MT-SNAPSHOT.jar:?]
    at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:294) ~[hadoop-hdfs-3.3.4-MT-SNAPSHOT.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.io.IOException: Failed to rename G:\data\hdfs\data\current\BP-1897851578-10.59.214.126-1624147212071\current\finalized\subdir5\subdir16\blk_16605581415_16555930755.meta to G:\data\hdfs\data\current\BP-1897851578-10.59.214.126-1624147212071\current\finalized\subdir5\subdir16\blk_16605581415_16557042956.meta due to failure in native rename. 32: The process cannot access the file because it is being used by another process.

    at org.apache.hadoop.hdfs.server.common.Storage.rename(Storage.java:1290) ~[hadoop-...