[HDDS-1351] NoClassDefFoundError when running ozone genconf (). Contributed by Doroszlai Attila.
This closes #659.

(cherry picked from commit 7dc0ecc446e3e58a795a925b3546b6d328b4eb02)