YARN-11390. TestResourceTrackerService.testNodeRemovalNormally: Shutdown nodes should be 0 now expected: <1> but was: <0>
- The hardcoded sleep what was used in the test was not the most stable solution
- It was replaced with a polling assert