YARN-10809. Missing dependency causing NoClassDefFoundError in TestHBaseTimelineStorageUtils (#3265)
* YARN-10809. Missing dependency causing NoClassDefFoundError in TestHBaseTimelineStorageUtils (#3081)

Reviewed-by: Takanobu Asanuma <tasanuma@apache.org>
(cherry picked from commit ca2774477052429a9d8371d66af9b7f7c007acd4)

* Use mockito 1.x

Co-authored-by: Viraj Jasani <vjasani@apache.org>