HADOOP-11927.  Fix "undefined reference to dlopen" error when compiling libhadooppipes (Xianyin Xin via Colin P. McCabe)
(cherry picked from commit f34638399abdca2e6d3bc5502508819dd747861c)