Revert "YARN-8856. TestTimelineReaderWebServicesHBaseStorage tests failing with NoClassDefFoundError. Contributed by Sushil Ks."
This reverts commit eeaf8edaa7d36715dfa00a29fe46e4c6de4b98cf.