HADOOP-15514. NoClassDefFoundError for TimelineCollectorManager when starting MiniYARNCluster. Contributed by Rohith Sharma K S.
(cherry picked from commit d1992ab9b01d6b2881abb2faae3dcab95d6fd996)