YARN-10314. YarnClient throws NoClassDefFoundError for WebSocketException with only shaded client jars (#2075)
(cherry picked from commit fc4ebb0499fe1095b87ff782c265e9afce154266)

Conflicts:
hadoop-client-modules/hadoop-client-minicluster/pom.xml
hadoop-client-modules/hadoop-client-runtime/pom.xml

Change-Id: I36f64efb911a16b865a6b4856bd0f8d595af1c97