HADOOP-19685. Fix double semicolon breaking clover
Removes the extra semicolon after an import that causes `-Pclover` to
fail with

    com.atlassian.clover.api.CloverException: hadoop/hadoop-tools/
    hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/impl/
    ITestS3APutIfMatchAndIfNoneMatch.java:43:43:unexpected token: ;`