YARN-10901. Fix permission checking error on an existing directory in LogAggregationFileController.
Create a temporary file with proper ownership to see if the underlying
file system supports chmod.

When the log directory was already created, but with a different user,
there was an exception in the log:

  org.apache.hadoop.security.AccessControlException: Permission denied.
  user=yarn is not the owner of inode=/tmp/logs

because the setPermission checked the ownership of the given path.

Change-Id: I7c7908b7ec815501337daaf7a2253a11d79afc8c